# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective username
ko_fi: # Replace with a single Ko-fi username
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username
issuehunt: # Replace with a single IssueHunt username
otechie: # Replace with a single Otechie username
custom: ["https://www.blockchain.com/btc/address/bc1qpssfv5vhgpwtyxj6aysdl5thzleqpagwm9nges", "https://www.blockchain.com/eth/address/0x38B30573DfbaE1CE32f1B3611E61c7f0D02803aA", "https://dogeblocks.com/address/DHS9xqJfdteChKiPxNjsUeUznAaZSwkt6A"]
